### ISSUE TITLE
Mojave Dark Mode

### ISSUE THREAD

**Issue by mxcl** [gitx/gitx#154]
I’ve started the work for dark-mode, mostly everything is good as is, with a small change for rendering the commit-list dots.

Main issue is the CSS, I figured we could set the `BODY` node to have a class like `dark-mode` and then for all the CSS we could provide eg:

```css
body.dark-mode .diff foo {
    color: white;
}
```

etc. Any thoughts on this?
